version: "3.9"

services:
  capstone:
    build: .
    container_name: capstone-data-pipeline
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: python scripts/data_download.py
