version: "3.9"

services:
  get_data:
    build: .
    container_name: capstone-data-pipeline
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: python scripts/data_download.py
  jupyter_notebook:
    build: .
    container_name: capstone-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    working_dir: /app/scripts
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=''

  streamlit-app:
    build: .
    container_name: streamlit-dashboard
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run scripts/combined_rainfall_yield_dashboard.py